# -*- coding: utf-8 -*-
#
# Copyright (C) 2021 Storm Project.
#
# storm-workbench is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

[tool.storm]

#
# Application name
#
name = "lulc-classification"

#
# Data Objects
#   > Dictionary with the definition of directories and files that should
#     be added/removed from/to the compendia zip file.
#
data_objects = { }

#
# Ignored Data Objects
#  > Dictionary with the definition of directories and files that should
#    be excluded from the ``inputs/outputs`` metadata definition. You can
#    use this argument to remove files like python modules scripts or cache
#    files loaded (which sometimes is detected as ``input``, for example).
#
ignored_data_objects = { }

#
# Ignored Environment Variables
#  > List with the environment variables that must be removed from the
#    reproducible bundle.
#
ignored_environment_variables = ["BDC_ACCESS_KEY"]

#
# Files Checksum Algorithm
#  > Checksum algorithm used to identify the files (default md5). This
#    implementation is provided by the ``Storm Hasher``.
#
#
files_checksum_algorithm = "md5"

[tool.storm.executor]

#
# Workbench execution scheduler
#
type = "paradag.parallel"
options = { n_process = 1 }
