name: base
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - abseil-cpp=20210324.2
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alembic=1.7.5
  - ansiwrap=0.8.4
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - async_generator=1.10
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - black=21.7b0
  - bleach=4.1.0
  - blinker=1.4
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - cairo=1.16.0
  - certifi=2022.6.15
  - certipy=0.1.3
  - cffi=1.15.0
  - cfitsio=3.470
  - charset-normalizer=2.0.10
  - click=8.0.3
  - colorama=0.4.4
  - conda=4.11.0
  - conda-package-handling=1.7.3
  - configurable-http-proxy=4.5.0
  - cryptography=36.0.1
  - cudatoolkit=11.6.0
  - cudnn=8.2.1.32
  - curl=7.81.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - executing=0.8.2
  - expat=2.4.3
  - flit-core=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.94
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - freexl=1.0.6
  - fribidi=1.0.10
  - frozenlist=1.3.0
  - gast=0.4.0
  - gcc_impl_linux-64=9.4.0
  - gcc_linux-64=9.4.0
  - gdal=3.3.1
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.4.0
  - gfortran_linux-64=9.4.0
  - giflib=5.2.1
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - greenlet=1.1.2
  - grpc-cpp=1.39.1
  - grpcio=1.39.0
  - gsl=2.7
  - gxx_impl_linux-64=9.4.0
  - gxx_linux-64=9.4.0
  - h5py=3.1.0
  - harfbuzz=3.1.1
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=68.2
  - idna=3.3
  - importlib-metadata=4.10.1
  - importlib_resources=5.4.0
  - ipykernel=6.7.0
  - ipython=8.0.1
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - jq=1.6
  - json-c=0.15
  - json5=0.9.5
  - jsonschema=4.4.0
  - jupyter_client=7.1.2
  - jupyter_core=4.9.1
  - jupyter_server=1.13.4
  - jupyter_telemetry=0.1.0
  - jupyterhub=2.1.0
  - jupyterhub-base=2.1.0
  - jupyterlab=3.2.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - kealib=1.4.14
  - keras=2.6.0
  - keras-preprocessing=1.1.2
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.19.2
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libarchive=3.5.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.81.0
  - libdap4=3.20.6
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-devel_linux-64=9.4.0
  - libgcc-ng=12.1.0
  - libgdal=3.3.1
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgit2=1.3.0
  - libglib=2.70.2
  - libgomp=12.1.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libmamba=0.19.1
  - libmambapy=0.19.1
  - libnetcdf=4.8.1
  - libnghttp2=1.43.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libpq=13.5
  - libprotobuf=3.16.0
  - librttopo=1.1.0
  - libsanitizer=9.4.0
  - libsodium=1.0.18
  - libsolv=0.7.19
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=9.4.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libuv=1.42.0
  - libv8=8.9.83
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - lzo=2.10
  - make=4.3
  - mako=1.1.6
  - mamba=0.19.1
  - markdown=3.3.6
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - multidict=6.0.2
  - mypy_extensions=0.4.3
  - nbclassic=0.3.5
  - nbclient=0.5.10
  - nbconvert=6.4.0
  - nbformat=5.1.3
  - nccl=2.11.4.1
  - ncurses=6.2
  - nest-asyncio=1.5.4
  - nodejs=14.17.4
  - notebook=6.4.7
  - numpy=1.19.5
  - oauthlib=3.1.1
  - oniguruma=6.9.7.1
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - opt_einsum=3.3.0
  - packaging=21.3
  - pamela=1.0.0
  - pandoc=2.17.0.1
  - pandocfilters=1.5.0
  - pango=1.48.10
  - papermill=2.3.4
  - parso=0.8.3
  - pathspec=0.9.0
  - pcre=8.45
  - pcre2=10.37
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.3.1
  - pixman=0.40.0
  - platformdirs=2.3.0
  - poppler=21.03.0
  - poppler-data=0.4.11
  - postgresql=13.5
  - proj=8.0.1
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.24
  - protobuf=3.16.0
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pybind11-abi=4
  - pycosat=0.6.3
  - pycparser=2.21
  - pycurl=7.44.1
  - pygments=2.11.2
  - pyjwt=2.3.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.7
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-flatbuffers=1.12
  - python-json-logger=2.0.1
  - python_abi=3.9
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=22.3.0
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.1.1
  - r-base64enc=0.1_3
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-brew=1.0_7
  - r-brio=1.1.3
  - r-cachem=1.0.6
  - r-callr=3.7.0
  - r-caret=6.0_90
  - r-class=7.3_20
  - r-classint=0.4_3
  - r-cli=3.1.1
  - r-clipr=0.7.1
  - r-codetools=0.2_18
  - r-colorspace=2.0_2
  - r-commonmark=1.7
  - r-covr=3.5.1
  - r-cpp11=0.4.2
  - r-crayon=1.4.2
  - r-credentials=1.3.2
  - r-crosstalk=1.2.0
  - r-crul=1.2.0
  - r-curl=4.3.2
  - r-data.table=1.14.2
  - r-dbi=1.1.2
  - r-desc=1.4.0
  - r-devtools=2.4.3
  - r-diffobj=0.3.5
  - r-digest=0.6.29
  - r-dplyr=1.0.7
  - r-dt=0.20
  - r-e1071=1.7_9
  - r-ellipsis=0.3.2
  - r-evaluate=0.14
  - r-fansi=1.0.2
  - r-farver=2.1.0
  - r-fastmap=1.1.0
  - r-foreach=1.5.2
  - r-foreign=0.8_82
  - r-fs=1.5.2
  - r-future=1.23.0
  - r-future.apply=1.8.1
  - r-gdalutils=2.0.3.2
  - r-generics=0.1.2
  - r-geojson=0.3.4
  - r-geojsonio=0.9.4
  - r-geojsonsf=2.0.1
  - r-geometries=0.2.0
  - r-gert=1.5.0
  - r-ggplot2=3.3.5
  - r-gh=1.3.0
  - r-git2r=0.29.0
  - r-gitcreds=0.1.1
  - r-globals=0.14.0
  - r-glue=1.6.1
  - r-gower=1.0.0
  - r-gtable=0.3.0
  - r-highr=0.9
  - r-hms=1.1.1
  - r-htmltools=0.5.2
  - r-htmlwidgets=1.5.4
  - r-httpcode=0.3.0
  - r-httr=1.4.2
  - r-ini=0.3.1
  - r-ipred=0.9_12
  - r-irdisplay=1.1
  - r-irkernel=1.3
  - r-isoband=0.2.5
  - r-iterators=1.0.14
  - r-jqr=1.2.2
  - r-jquerylib=0.1.4
  - r-jsonify=1.2.1
  - r-jsonlite=1.7.3
  - r-kernsmooth=2.23_20
  - r-knitr=1.37
  - r-labeling=0.4.2
  - r-later=1.2.0
  - r-lattice=0.20_45
  - r-lava=1.6.10
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.1
  - r-listenv=0.8.0
  - r-lubridate=1.8.0
  - r-magrittr=2.0.2
  - r-maptools=1.1_2
  - r-mass=7.3_55
  - r-matrix=1.4_0
  - r-memoise=2.0.1
  - r-mgcv=1.8_38
  - r-mime=0.12
  - r-modelmetrics=1.2.2.2
  - r-munsell=0.5.0
  - r-nlme=3.1_155
  - r-nnet=7.3_17
  - r-numderiv=2016.8_1.1
  - r-openssl=1.4.6
  - r-parallelly=1.30.0
  - r-pbdzmq=0.3_6
  - r-pillar=1.6.5
  - r-pkgbuild=1.3.1
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.4
  - r-plyr=1.8.6
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-proc=1.18.0
  - r-processx=3.5.2
  - r-prodlim=2019.11.13
  - r-progress=1.2.2
  - r-progressr=0.10.0
  - r-promises=1.2.0.1
  - r-protolite=2.1.1
  - r-proxy=0.4_26
  - r-ps=1.6.0
  - r-purrr=0.3.4
  - r-r.methodss3=1.8.1
  - r-r.oo=1.24.0
  - r-r.utils=2.11.0
  - r-r6=2.5.1
  - r-rapidjsonr=1.2.0
  - r-rappdirs=0.3.3
  - r-raster=3.5_15
  - r-rcmdcheck=1.4.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.8.3
  - r-readr=2.1.2
  - r-recipes=0.1.17
  - r-rematch2=2.1.2
  - r-remotes=2.4.2
  - r-renv=0.15.2
  - r-repr=1.1.4
  - r-reshape2=1.4.4
  - r-rex=1.2.1
  - r-rgdal=1.5_23
  - r-rgeos=0.5_8
  - r-rlang=0.4.12
  - r-roxygen2=7.1.2
  - r-rpart=4.1.16
  - r-rprojroot=2.0.2
  - r-rstudioapi=0.13
  - r-rversions=2.1.1
  - r-s2=1.0.7
  - r-scales=1.1.1
  - r-sessioninfo=1.2.2
  - r-sf=1.0_2
  - r-sfheaders=0.4.0
  - r-sp=1.4_6
  - r-squarem=2021.1
  - r-stringi=1.7.6
  - r-stringr=1.4.0
  - r-survival=3.2_13
  - r-sys=3.4
  - r-terra=1.3_22
  - r-testthat=3.1.2
  - r-tibble=3.1.6
  - r-tidyr=1.2.0
  - r-tidyselect=1.1.1
  - r-timedate=3043.102
  - r-triebeard=0.3.0
  - r-tzdb=0.2.0
  - r-units=0.7_2
  - r-urltools=1.7.3
  - r-usethis=2.1.5
  - r-utf8=1.2.2
  - r-uuid=1.0_3
  - r-v8=4.0.0
  - r-vctrs=0.3.8
  - r-viridislite=0.4.0
  - r-vroom=1.5.7
  - r-waldo=0.3.1
  - r-whisker=0.4
  - r-withr=2.4.3
  - r-wk=0.6.0
  - r-xfun=0.29
  - r-xml=3.99_0.9
  - r-xml2=1.3.3
  - r-xopen=1.0.0
  - r-yaml=2.2.2
  - r-zip=2.2.0
  - re2=2021.09.01
  - readline=8.1
  - regex=2022.1.18
  - reproc=14.2.3
  - reproc-cpp=14.2.3
  - requests=2.27.1
  - requests-oauthlib=1.3.0
  - rsa=4.8
  - ruamel.yaml=0.17.19
  - ruamel.yaml.clib=0.2.6
  - ruamel_yaml=0.15.80
  - scipy=1.7.3
  - sed=4.8
  - send2trash=1.8.0
  - setuptools=60.5.0
  - six=1.15.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - sqlalchemy=1.4.31
  - sqlite=3.37.0
  - stack_data=0.1.4
  - sysroot_linux-64=2.12
  - tenacity=8.0.1
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.6.0
  - tensorflow-base=2.6.0
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - terminado=0.12.1
  - testpath=0.5.0
  - textwrap3=0.9.2
  - tiledb=2.3.4
  - tk=8.6.11
  - tktable=2.10
  - tomli=1.2.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typed-ast=1.5.1
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzcode=2021e
  - tzdata=2021e
  - udunits2=2.2.27.27
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.2.3
  - werkzeug=2.0.2
  - wheel=0.37.1
  - wrapt=1.12.1
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yaml-cpp=0.6.3
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
