datacube:
  start_date: "2000-09-13"
  end_date: "2016-08-28"
  collection: "MOD13Q1-6"
  bands:
    - "NDVI"
    - "EVI"
    - "NIR_reflectance"
    - "MIR_reflectance"
    - "red_reflectance"
    - "blue_reflectance"
    - "pixel_reliability"

resources:
  memsize: 120
  multicores: 30

files:
  base_input_directory: "data/raw_data/modis-mato_grosso"
  base_output_directory: "data/derived_data/modis-mato_grosso"
