name: build_bdc-article

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push (BDC Article)
      uses: docker/build-push-action@v2
      with:
        context: applications/bdc-article/compendium
        push: true
        tags: stormproject/pkg-bdc-article:0.1
