name: build_bdc-article

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push (BDC Article)
      uses: docker/build-push-action@v2
      with:
        context: applications/bdc-article/compendium
        push: true
        tags: stormproject/pkg-bdc-article:0.1

    - name: Timestamp
      run: mkdir -p build && date --rfc-3339=seconds > .github/log/last_build_bdc-article.txt

    - name: Commit and push
      uses: EndBug/add-and-commit@v7
      with:
        add: ".github/log/last_build_bdc-article.txt"
        push: true
        committer_name: GitHub Actions
        committer_email: actions@github.com
